import { I_Experience, I_Project } from "@/src/types/type";

export const words = [
  "Product Management Enthusiast",
  "Business Analyst",
  "Data-Driven Decision Maker",
  "Strategic Problem Solver",
];

export const experienceData: I_Experience[] = [
  {
    company_link: "#",
    company_logo: "/assets/image.png",
    company_name: "Analytics Resources",
    duration: "Jun 2025 - Aug 2025",
    job_title: "Data Analyst Intern",
    description: "Integrated product APIs and performed statistical analysis to drive data-driven insights and optimize revenue strategies.",
    highlights: [
      "Integrated Product APIs from Amazon, Flipkart, Myntra, and travel platforms to extract 10K+ product and travel records using ETL pipelines for data cleaning, transformation, and exploratory analysis",
      "Conducted statistical analysis to identify seasonal trends, category performance patterns, and profit optimization opportunities, delivering actionable insights that enhanced revenue strategies",
      "Developed analytical dashboards and curated recommendation systems to enable data-driven decision making and deliver personalized user experiences across e-commerce and travel platforms",
      "Implemented automated data workflows reducing manual processing time and improving data accuracy by streamlining ETL processes",
      "Collaborated with cross-functional teams to translate business requirements into analytical solutions and measurable outcomes"
    ]
  },
  {
    company_link: "#",
    company_logo: "/assets/image.png",
    company_name: "Zuraverse (Web3 Gaming & Metaverse Platform)",
    duration: "Dec 2024 - Jan 2025",
    job_title: "Business Analyst Intern",
    description: "Leveraged data analytics and Agile methodologies to drive product decisions in Web3 gaming ecosystem.",
    highlights: [
      "Analyzed user engagement and product metrics to identify behavioral trends, improving data-driven decision-making for growth and retention strategies",
      "Collaborated with cross-functional teams in an Agile/Scrum environment to define business requirements, user stories, and product KPIs for new feature rollouts",
      "Conducted market and competitive analysis on Web3 and NFT gaming platforms, delivering insights that informed product roadmap and tokenomics strategy",
      "Built interactive dashboards and reports using Excel and Tableau to track platform performance and operational KPIs, enabling leadership to optimize resource allocation",
      "Facilitated sprint retrospectives and requirement gathering sessions to translate stakeholder needs into actionable product backlogs and data analytics initiatives"
    ]
  },
  {
    company_link: "#",
    company_logo: "/assets/image.png",
    company_name: "OMELO (Pet Care Startup)",
    duration: "Sep 2024 - Nov 2024",
    job_title: "Growth & Strategy Intern",
    description: "Drove product growth initiatives and collaborated with cross-functional teams to enhance user engagement and retention.",
    highlights: [
      "Conducted comprehensive market and competitor analysis to identify strategic growth opportunities, leading to successful onboarding of 12 niche influencers and acquisition of 500+ active users within 6 weeks",
      "Collaborated with product and marketing teams to design and launch 3 user engagement initiatives, resulting in 40% improvement in user retention and 25% month-over-month lead growth",
      "Translated user feedback and pain points into actionable product requirements, streamlining onboarding workflows and increasing feature adoption by 30%",
      "Developed data-driven growth strategies by analyzing user behavior metrics and market trends to inform product roadmap decisions",
      "Facilitated cross-functional alignment between product, marketing, and customer success teams to ensure cohesive execution of growth initiatives"
    ]
  },
];

export const projects: I_Project[] = [
  {
    title: "Formula 1 World Championship Data Analysis",
    description: "ML-powered F1 racing analysis achieving 100% accuracy with Random Forest classification.",
    tech: ["Python", "Pandas", "Scikit-learn", "Machine Learning", "Data Visualization", "Folium"],
    status: "Completed",
    year: "2024",
    link: "https://github.com/SakCo/F1-WorldChampDataAnalysis",
    code: "https://github.com/SakCo/F1-WorldChampDataAnalysis",
    imageSrc: "/projects/f1ProjectImage.webp",
  },
  {
    title: "SQL Data Warehouse and Analytics Project",
    description: "End-to-end data warehouse using Medallion Architecture with ETL pipelines and star schema design.",
    tech: ["SQL Server", "T-SQL", "ETL", "Data Modeling", "Star Schema", "Business Intelligence"],
    status: "Completed",
    year: "2024",
    link: "https://github.com/SakCo/Advance-DataWarehouse-Project",
    code: "https://github.com/SakCo/Advance-DataWarehouse-Project",
    imageSrc: "/projects/dw.jpg",
  },
  {
    title: "IBM Employee Attrition Analysis",
    description: "Predictive HR analytics achieving 87% accuracy using Random Forest and SMOTE.",
    tech: ["Python", "Pandas", "Scikit-learn", "SMOTE", "Random Forest", "Data Visualization"],
    status: "Completed",
    year: "2024",
    link: "https://github.com/SakCo/IBM-Employee-Attrition-Analysis",
    code: "https://github.com/SakCo/IBM-Employee-Attrition-Analysis",
    imageSrc: "/projects/ibm2.jpg",
  },
  {
    title: "Netflix Data Analysis",
    description: "Strategic content analytics using Python for genre trends and performance benchmarking.",
    tech: ["Python", "Pandas", "NumPy", "Matplotlib", "Seaborn", "Data Visualization"],
    status: "Completed",
    year: "2024",
    link: "https://github.com/SakCo/NetflixDataAnalysis",
    code: "https://github.com/SakCo/NetflixDataAnalysis",
    imageSrc: "/projects/netflix2ProjectImage.jpg",
  },
  {
    title: "Netflix Analysis and Prediction",
    description: "Content performance prediction achieving 85% accuracy using machine learning models.",
    tech: ["Python", "Pandas", "Scikit-learn", "Random Forest", "Matplotlib", "Seaborn"],
    status: "Completed",
    year: "2024",
    link: "https://github.com/SakCo/NetflixAnalysisAndPrediction",
    code: "https://github.com/SakCo/NetflixAnalysisAndPrediction",
    imageSrc: "/projects/netfixProjectImage.webp",
  },
  {
    title: "HomeStay Cancellation Root Cause Analysis",
    description: "Root cause analysis of booking cancellations using data analytics and statistical methods.",
    tech: ["Python", "Excel", "Data Analysis", "Root Cause Analysis", "Statistical Methods"],
    status: "Completed",
    year: "2024",
    link: "https://github.com/SakCo/HomeStayCancellation-RootCause-Analysis",
    code: "https://github.com/SakCo/HomeStayCancellation-RootCause-Analysis",
    imageSrc: "/projects/rca.jpg",
  },
  // {
  //   title: "Competitive Analysis Report",
  //   description: "In-depth competitive landscape analysis and positioning strategy.",
  //   tech: ["Market Analysis", "SWOT", "Porter's Five Forces"],
  //   status: "Completed",
  //   year: "2024",
  //   link: "#",
  //   code: "#",
  //   imageSrc: "/projects/portfolio.png",
  // },
  // {
  //   title: "Revenue Forecasting Model",
  //   description: "Predictive analytics model for revenue projections and trends.",
  //   tech: ["Excel", "Forecasting", "Financial Modeling"],
  //   status: "In Progress",
  //   year: "2024",
  //   link: "#",
  //   code: "#",
  //   imageSrc: "/projects/finboard.png",
  // },
  // {
  //   title: "Customer Journey Mapping",
  //   description: "End-to-end customer experience analysis and optimization.",
  //   tech: ["UX Research", "Journey Mapping", "Persona Development"],
  //   status: "Completed",
  //   year: "2024",
  //   link: "#",
  //   code: "#",
  //   imageSrc: "/projects/grocery.png",
  // },
  // {
  //   title: "SQL Data Analysis Project",
  //   description: "Complex SQL queries for business insights and reporting.",
  //   tech: ["SQL", "Database Design", "Query Optimization"],
  //   status: "Live",
  //   year: "2024",
  //   link: "#",
  //   code: "https://github.com/SakCo",
  //   imageSrc: "/projects/animeflix.png",
  // },
];

// };

export const caseStudies: I_Project[] = [
  {
    title: "How Lenskart Outsmarted Tata Eyewear Brands",
    description: "Strategic analysis of Lenskart's digital-first disruption defeating legacy competitors.",
    tech: ["Competitive Analysis", "Business Strategy", "Market Research", "Product Management"],
    status: "Completed",
    year: "2024",
    link: "https://medium.com/@sakshi.s.singh2003/how-lenskart-outsmarted-tata-eyewear-brands-5dad1a511066",
    code: "https://medium.com/@sakshi.s.singh2003/how-lenskart-outsmarted-tata-eyewear-brands-5dad1a511066",
    imageSrc: "/projects/lenskart2.jpg",
    metrics: "Digital disruption, Omnichannel strategy, Customer-centric innovation",
    isMedium: true,
  },
  {
    title: "The Race of AI Trading - Decoding the New Era of Trading",
    description: "Business analysis of AI-driven trading systems transforming financial markets.",
    tech: ["AI/ML Strategy", "Predictive Analytics", "Business Impact Analysis", "Financial Technology"],
    status: "Completed",
    year: "2024",
    link: "https://medium.com/@sakshi.s.singh2003/the-race-of-ai-trading-decoding-the-new-era-of-trading-a69914f7dd2f",
    code: "https://medium.com/@sakshi.s.singh2003/the-race-of-ai-trading-decoding-the-new-era-of-trading-a69914f7dd2f",
    imageSrc: "/projects/ai.jpg",
    metrics: "20-30% performance improvement, 40% cost reduction, 24/7 automation",
    isMedium: true,
  },
  {
    title: "How Spotify Outplayed Gaana and JioSaavn",
    description: "Strategic market entry analysis of Spotify conquering India's music market.",
    tech: ["Market Entry Strategy", "Localization", "Product Positioning", "Competitive Analysis"],
    status: "Completed",
    year: "2024",
    link: "https://medium.com/@sakshi.s.singh2003/how-spotify-outplayed-gaana-and-jiosaavn-winning-indias-music-market-as-a-foreign-brand-a70076d7c6db",
    code: "https://medium.com/@sakshi.s.singh2003/how-spotify-outplayed-gaana-and-jiosaavn-winning-indias-music-market-as-a-foreign-brand-a70076d7c6db",
    imageSrc: "/projects/spotify.jpg",
    metrics: "Market leadership, AI-driven personalization, Multi-regional expansion",
    isMedium: true,
  },
  {
    title: "Redesigning JioMart - The Missed Opportunity",
    description: "Product redesign case study for JioMart's grocery-first repositioning strategy.",
    tech: ["Product Strategy", "UX/UI Redesign", "Business Analysis", "Market Positioning"],
    status: "Completed",
    year: "2024",
    link: "https://medium.com/@sakshi.s.singh2003/case-study-redesigning-jiomart-the-missed-opportunity-in-indias-online-retail-boom-d09252723b1e",
    code: "https://medium.com/@sakshi.s.singh2003/case-study-redesigning-jiomart-the-missed-opportunity-in-indias-online-retail-boom-d09252723b1e",
    imageSrc: "/projects/jiomart.jpg",
    metrics: "Strategic focus, Kirana empowerment, AI-driven recommendations",
    isMedium: true,
  },
  {
    title: "Data-Driven Pricing Strategy",
    description: "Optimized pricing model using elasticity analysis, increasing revenue by 22%.",
    tech: ["Pricing Strategy", "Statistical Analysis", "Excel", "Revenue Optimization"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/portfolio.png",
    metrics: "22% revenue increase, 15% margin improvement",
  },
  {
    title: "Product Metrics Dashboard",
    description: "Built comprehensive analytics dashboard tracking 50+ product KPIs in real-time.",
    tech: ["Product Analytics", "Tableau", "SQL", "KPI Framework"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "https://github.com/SakCo",
    imageSrc: "/projects/finboard.png",
    metrics: "50+ KPIs tracked, 10 stakeholder teams enabled",
  },
];
