import { I_Experience } from "@/src/types/type";

export const words = [
  "Product Management Enthusiast",
  "Business Analyst",
  "Data-Driven Decision Maker",
  "Strategic Problem Solver",
];

export const experienceData: I_Experience[] = [
  {
    company_link: "#",
    company_logo: "/assets/image.png",
    company_name: "Product Management Internship",
    duration: "Jan 2024 - Jun 2024",
    job_title: "Product Management Intern",
    description: "Led product discovery initiatives and conducted user research to identify pain points. Collaborated with cross-functional teams to define product requirements and prioritize features based on business impact.",
    highlights: [
      "Led user research initiatives with 50+ interviews to identify key pain points and feature requests",
      "Collaborated with engineering, design, and marketing teams to launch 3 major product features",
      "Developed product roadmaps and prioritization frameworks using RICE scoring methodology",
      "Created go-to-market strategies resulting in 25% increase in user engagement",
      "Analyzed user behavior data and conducted A/B tests to optimize conversion funnels"
    ]
  },
  {
    company_link: "#",
    company_logo: "/assets/image.png",
    company_name: "Analytics Internship",
    duration: "Jul 2023 - Dec 2023",
    job_title: "Business Analytics Intern",
    description: "Analyzed large datasets to extract actionable insights and drive business decisions. Created comprehensive dashboards and reports using data visualization tools.",
    highlights: [
      "Analyzed 100K+ customer records to identify key segments and behavioral patterns",
      "Built interactive dashboards in Tableau tracking 20+ KPIs for executive stakeholders",
      "Conducted statistical analysis and hypothesis testing to validate business assumptions",
      "Automated monthly reporting processes, reducing manual work by 15 hours per month",
      "Presented data-driven insights to leadership, influencing strategic decisions"
    ]
  },
];

export const projects = [
  {
    title: "Market Research Analysis",
    description: "Comprehensive market analysis for product positioning strategy.",
    tech: ["Market Research", "Competitive Analysis", "Data Visualization"],
    status: "Completed",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/grocery.png",
  },
  {
    title: "User Behavior Analytics",
    description: "Data-driven insights dashboard tracking user engagement metrics.",
    tech: ["Analytics", "SQL", "Tableau", "Python"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "https://github.com/SakCo",
    imageSrc: "/projects/animeflix.png",
  },
  {
    title: "Product Roadmap & Strategy",
    description: "Strategic product planning with feature prioritization framework.",
    tech: ["Product Strategy", "Agile", "Stakeholder Management"],
    status: "In Development",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/medichain.png",
  },
  {
    title: "Customer Segmentation Study",
    description: "Advanced customer segmentation using RFM analysis and clustering.",
    tech: ["Python", "Machine Learning", "Data Analysis", "Excel"],
    status: "Completed",
    year: "2024",
    link: "#",
    code: "https://github.com/SakCo",
    imageSrc: "/projects/crypto.png",
  },
  {
    title: "A/B Testing Framework",
    description: "Statistical testing framework for product optimization.",
    tech: ["Statistics", "Hypothesis Testing", "Data Analysis"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "https://github.com/SakCo",
    imageSrc: "/projects/notes.png",
  },
  {
    title: "Business Intelligence Dashboard",
    description: "Real-time KPI tracking dashboard for business performance.",
    tech: ["Power BI", "SQL", "DAX", "ETL"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/landing.png",
  },
  {
    title: "Competitive Analysis Report",
    description: "In-depth competitive landscape analysis and positioning strategy.",
    tech: ["Market Analysis", "SWOT", "Porter's Five Forces"],
    status: "Completed",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/portfolio.png",
  },
  {
    title: "Revenue Forecasting Model",
    description: "Predictive analytics model for revenue projections and trends.",
    tech: ["Excel", "Forecasting", "Financial Modeling"],
    status: "In Progress",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/finboard.png",
  },
  {
    title: "Customer Journey Mapping",
    description: "End-to-end customer experience analysis and optimization.",
    tech: ["UX Research", "Journey Mapping", "Persona Development"],
    status: "Completed",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/grocery.png",
  },
  {
    title: "SQL Data Analysis Project",
    description: "Complex SQL queries for business insights and reporting.",
    tech: ["SQL", "Database Design", "Query Optimization"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "https://github.com/SakCo",
    imageSrc: "/projects/animeflix.png",
  },
];

export const caseStudies = [
  {
    title: "E-Commerce Platform Optimization",
    description: "Increased conversion rate by 35% through data-driven UX improvements and A/B testing.",
    tech: ["Product Strategy", "A/B Testing", "Analytics", "User Research"],
    status: "Completed",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/medichain.png",
    metrics: "35% increase in conversion rate, 50% reduction in cart abandonment",
  },
  {
    title: "Mobile App Feature Launch",
    description: "Led end-to-end product development for new feature driving 10K+ daily active users.",
    tech: ["Product Management", "Agile", "Stakeholder Management", "Go-to-Market"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/crypto.png",
    metrics: "10K+ DAU, 4.8★ App Store rating, 25% engagement increase",
  },
  {
    title: "Customer Churn Reduction Strategy",
    description: "Developed predictive model and retention strategy reducing churn by 28%.",
    tech: ["Predictive Analytics", "Python", "Machine Learning", "Business Strategy"],
    status: "Completed",
    year: "2024",
    link: "#",
    code: "https://github.com/SakCo",
    imageSrc: "/projects/notes.png",
    metrics: "28% churn reduction, $500K+ annual revenue retention",
  },
  {
    title: "Market Entry Analysis - Fintech",
    description: "Comprehensive market research and GTM strategy for fintech product launch.",
    tech: ["Market Research", "Competitive Analysis", "GTM Strategy", "Financial Modeling"],
    status: "Completed",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/landing.png",
    metrics: "Identified $50M market opportunity, 3 strategic partnerships",
  },
  {
    title: "Data-Driven Pricing Strategy",
    description: "Optimized pricing model using elasticity analysis, increasing revenue by 22%.",
    tech: ["Pricing Strategy", "Statistical Analysis", "Excel", "Revenue Optimization"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "#",
    imageSrc: "/projects/portfolio.png",
    metrics: "22% revenue increase, 15% margin improvement",
  },
  {
    title: "Product Metrics Dashboard",
    description: "Built comprehensive analytics dashboard tracking 50+ product KPIs in real-time.",
    tech: ["Product Analytics", "Tableau", "SQL", "KPI Framework"],
    status: "Live",
    year: "2024",
    link: "#",
    code: "https://github.com/SakCo",
    imageSrc: "/projects/finboard.png",
    metrics: "50+ KPIs tracked, 10 stakeholder teams enabled",
  },
];
